[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "pdns-singularity"
version = "0.1.0"

[dependencies]
anyhow = "1.0.32"
confy = "0.4.0"
fern = "0.6.0"
log = "0.4.11"
serde = {version = "1.0.115", features = ["derive"]}
structopt = "0.3.17"
url = {version = "2.1.1", features = ["serde"]}
