[package]
authors = ["Spanfile <spansdev@gmail.com>"]
categories = ["command-line-interface"]
description = "CLI tool for pulling known malicious domains into a blackhole list."
edition = "2018"
homepage = "https://git.spans.me/Spanfile/singularity"
keywords = ["cli", "dns", "blackhole"]
license = "MIT"
name = "singularity"
readme = "README.md"
repository = "https://git.spans.me/Spanfile/singularity"
version = "0.2.0"

[dependencies]
anyhow = "1.0.32"
chrono = "0.4.15"
confy = "0.4.0"
fern = "0.6.0"
log = "0.4.11"
serde = {version = "1.0.115", features = ["derive"]}
structopt = "0.3.17"
thiserror = "1.0.20"
ureq = "1.4.0"
url = {version = "2.1.1", features = ["serde"]}
