[package]
authors = ["Spanfile <spansdev@gmail.com>"]
categories = ["command-line-interface"]
description = "CLI tool for pulling known malicious domains into one or more blackhole lists in various formats."
edition = "2018"
keywords = ["cli", "dns", "blackhole"]
license = "MIT"
name = "singularity"
readme = "README.md"
repository = "https://github.com/Spanfile/Singularity"
version = "0.5.1"

[dependencies]
anyhow = "1.0.32"
chrono = "0.4.15"
confy = "0.4.0"
fern = "0.6.0"
indicatif = {version = "0.15.0", features = ["improved_unicode"]}
log = "0.4.11"
serde = {version = "1.0.116", features = ["derive"]}
structopt = "0.3.17"
tempfile = "3.1.0"
thiserror = "1.0.20"
ureq = "1.4.1"
url = {version = "2.1.1", features = ["serde"]}
