comment_width = 120
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
max_width = 120
merge_derives = true
normalize_comments = true
unstable_features = true
version = "Two"
wrap_comments = true
